# -*- coding: utf-8 -*-
import os
import re

directories = [
    'src',
    'backend/app',
    'scripts',
    'frontend/src',
    'data_gen'
]
individual_files = ['app.py']

# Let's find comments (Python: starting with #, JS/TS: starting with // or inside /* */)
# And search for patterns like:
# - generated by AI/gpt/copilot/gemini
# - AI generated
# - copilot
# - code created by
# - auto-generated comments

patterns = [
    re.compile(r'generated\s+by\s+(gpt|ai|copilot|gemini|assistant|claude|llm)', re.IGNORECASE),
    re.compile(r'ai[-_ ]generated', re.IGNORECASE),
    re.compile(r'auto[-_ ]generated\s+by', re.IGNORECASE),
    re.compile(r'created\s+by\s+(gpt|ai|copilot|gemini|assistant|llm)', re.IGNORECASE),
    re.compile(r'written\s+by\s+(gpt|ai|copilot|gemini|assistant|llm)', re.IGNORECASE),
    re.compile(r'#.*(copilot|assistant|gpt|gemini|claude)\s+code', re.IGNORECASE),
    # Let's also scan for generic robot-like phrases in comments:
    re.compile(r'#\s*(this\s+file|this\s+script|this\s+code|the\s+following)\s+(is|was)\s+(generated|created|written)\b', re.IGNORECASE),
]

all_paths = []
for d in directories:
    if os.path.exists(d):
        for root, dirs, files in os.walk(d):
            # Skip node_modules, __pycache__, .git
            if any(x in root for x in ['node_modules', '__pycache__', '.git', '.venv']):
                continue
            for f in files:
                if f.endswith(('.py', '.js', '.jsx', '.ts', '.tsx', '.json', '.html', '.css')):
                    all_paths.append(os.path.join(root, f))

for f in individual_files:
    if os.path.exists(f):
        all_paths.append(f)

print(f"Scanning {len(all_paths)} source files...")

found = False
for path in all_paths:
    try:
        with open(path, 'r', encoding='utf-8', errors='ignore') as file:
            lines = file.readlines()
        for idx, line in enumerate(lines):
            # Check if line is a comment or contains matching patterns
            for pattern in patterns:
                if pattern.search(line):
                    print(f"Found potential AI signature in {path} at line {idx+1}:")
                    print(f"  > {line.strip()}")
                    found = True
    except Exception as e:
        print(f"Error scanning {path}: {e}")

if not found:
    print("No potential AI signatures found in source code comments.")
